### ISSUE TITLE
KeyValuePair support?

### ISSUE THREAD

**Issue by CRC32EX** [Cysharp/WebSerializer#5]
# Steps to reproduce this issue
### Source code
```cs
var parameters = new KeyValuePair<string, string>[]
{
    new ("id", "1"),
    new ("name", "tanaka"),
    new ("email", "test@example.com")
};

Console.WriteLine(WebSerializer.ToQueryString("https://example.com/user", parameters));
```

### Output
```txt
https://example.com/user?Key=id&Value=1&Key=name&Value=tanaka&Key=email&Value=test@example.com
```

### What I expected Output
```txt
https://example.com/user?id=1&name=tanaka&email=test%40example.com
```

# Note
- I don't want to use `Dictionary`.<br>Because some web application take same parameter name.<br>ex.) `id=1&id=2&id=3`

# Environment
- Visual Studio Community 2022 (64bit)
- .NET 6.0.101
- WebSerializer 1.1.0

**Comment by neuecc** [comment]
Thank you for the request.
It is nice feature!
I've released `1.2.0`, it supports that you expected.
