### ISSUE TITLE
.NET Standard support?

### ISSUE THREAD

**Issue by CRC32EX** [Cysharp/WebSerializer#6]
> Supporting platform is .NET 5, .NET 6.
> [README.md](https://github.com/Cysharp/WebSerializer/blob/master/README.md)

I know this library currently supporting platform is .NET 5, .NET 6.
Could you have a plan to supports .NET Standard?

**Comment by neuecc** [comment]
OK, I've released 1.3.0 that supports .NET Standard 2.0 and 2.1.
